name: Test_react_app
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4
      - name: install dependency env
        run: npm ci
      - name: check some tests
        run: npm run test
  eslnt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4
      - name: install dependency env
        run: npm ci
      - name: check Eslint
        run: npm run lint
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4
      - name: install dependency env
        run: npm ci
      - name: build app
        run: npm run build
