name: Test_react_app1
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4
      - name: caching tests
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: install dependency env
        run: npm ci
      - name: check some tests
        run: npm run test
  eslint:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4
      - name: caching data
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: install dependency env
        run: npm ci
      - name: check Eslint
        run: npm run lint
  build_deploy:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4
      - name: caching data of deploy
        uses: actions/cache@v3
        with:
          path: ./build
          key: deploy-${{ hashFiles('**/build/**') }}
      - name: install dependency env
        run: npm ci
      - name: build app
        run: npm run build
